[package]
name = "rowscript"
version = "0.9.0"
edition = "2021"

[features]
default = ["codegen-ecma"]
codegen-ecma = ["rowscript-core/codegen-ecma"]

[dependencies.rowscript-core]
path = "../core"
default-features = false

[dependencies.clap]
version = "4.0"
features = ["derive"]
