[package]
name = "rowscript-core"
version = "0.8.0"
edition = "2021"

[features]
default = ["codegen-es6"]
codegen-es6 = []

[dependencies.pest]
version = "2.4.1"
features = ["fast-line-col"]

[dependencies.pest_derive]
version = "2.4.1"

[dependencies.thiserror]
version = "1.0.37"

[dependencies.ariadne]
version = "0.2.0"

[dev-dependencies.swc_ecma_parser]
version = "0.132.5"

[dev-dependencies.swc_common]
version = "0.30.4"
features = ["tty-emitter"]
