[package]
name = "rowscript_core"
version = "0.1.0"
edition = "2021"

[dependencies.pest]
version = "2.4.1"

[dependencies.pest_derive]
version = "2.4.1"

[dependencies.uuid]
version = "1.2.1"
features = [
    "v4",
    "fast-rng",
]
