[package]
name = "rowscript-core"
version = "0.1.0"
edition = "2018"
authors = ["RowScript developers"]
license = "MIT"
description = "RowScript core theory"
readme = "README.md"
categories = ["development-tools"]
repository = "https://github.com/rowscript/rowscript"

[dependencies]
